name: Staging

on:
    workflow_dispatch:

    push:
        branches:
            - staging

    pull_request:
        branches:
            - staging

jobs:
    Staging:
        runs-on: ubuntu-latest
        env:
            AGE: ${{ secrets.AGE }}
            TMP: /tmp
            TZ: Asia/Dhaka

        steps:
            - name: Global Config
              run: |
                  echo

                  git config --global user.name "Izumi Sena Sora"
                  git config --global user.email "61591769+IzumiSenaSora@users.noreply.github.com"
                  git config --global init.defaultBranch main
                  git config --global pull.rebase false
                  git config --global core.eol lf
                  git config --global core.autocrlf input
                  git config --global http.postBuffer 1048576000
                  git config --global filter.crypt.smudge "openssl enc -d -chacha20 -S f6735bf5d3c9ed33 -a -pbkdf2 -pass env:AGE -"
                  git config --global filter.crypt.clean "openssl enc -chacha20 -salt -a -S f6735bf5d3c9ed33 -pbkdf2 -pass env:AGE -"
                  git config --global filter.crypt.required true

            - uses: actions/checkout@v4

            - name: Run Actions
              run: |
                  echo

                  if [[ -f scripts/actions.sh ]]; then
                      bash scripts/actions.sh
                  fi

        timeout-minutes: 5
